CREATE TYPE public.app_role AS ENUM ('admin','tutor','student');
CREATE TYPE public.application_status AS ENUM ('pending','approved','rejected','changes_requested');
CREATE TYPE public.access_level AS ENUM ('free','premium');
CREATE TYPE public.booking_status AS ENUM ('pending','confirmed','completed','cancelled');
CREATE TYPE public.payment_status AS ENUM ('pending','paid','failed','refunded');

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$ BEGIN NEW.updated_at=now(); RETURN NEW; END; $$;

CREATE TABLE public.profiles (id uuid PRIMARY KEY, full_name text NOT NULL DEFAULT '', email text NOT NULL DEFAULT '', phone text, avatar_url text, country text, preferences jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role; ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles own read" ON public.profiles FOR SELECT TO authenticated USING (auth.uid()=id); CREATE POLICY "profiles own create" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid()=id); CREATE POLICY "profiles own update" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid()=id) WITH CHECK (auth.uid()=id);

CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL DEFAULT 'student', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role; ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "roles own read" ON public.user_roles FOR SELECT TO authenticated USING (auth.uid()=user_id);
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
CREATE OR REPLACE FUNCTION public.is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.has_role(auth.uid(),'admin') $$;

CREATE TABLE public.programs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, description text NOT NULL, accent text NOT NULL DEFAULT 'blue', is_published boolean NOT NULL DEFAULT true, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.programs TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.programs TO authenticated; GRANT ALL ON public.programs TO service_role; ALTER TABLE public.programs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "programs public read" ON public.programs FOR SELECT USING (is_published OR public.is_admin()); CREATE POLICY "programs admin manage" ON public.programs FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE TABLE public.subjects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), program_id uuid NOT NULL REFERENCES public.programs(id) ON DELETE CASCADE, name text NOT NULL, slug text NOT NULL, description text NOT NULL, is_published boolean NOT NULL DEFAULT true, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(program_id,slug));
GRANT SELECT ON public.subjects TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.subjects TO authenticated; GRANT ALL ON public.subjects TO service_role; ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "subjects public read" ON public.subjects FOR SELECT USING (is_published OR public.is_admin()); CREATE POLICY "subjects admin manage" ON public.subjects FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE TABLE public.topics (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject_id uuid NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE, name text NOT NULL, slug text NOT NULL, description text NOT NULL DEFAULT '', is_published boolean NOT NULL DEFAULT true, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(subject_id,slug));
GRANT SELECT ON public.topics TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.topics TO authenticated; GRANT ALL ON public.topics TO service_role; ALTER TABLE public.topics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "topics public read" ON public.topics FOR SELECT USING (is_published OR public.is_admin()); CREATE POLICY "topics admin manage" ON public.topics FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE TABLE public.resources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), program_id uuid NOT NULL REFERENCES public.programs(id), subject_id uuid NOT NULL REFERENCES public.subjects(id), topic_id uuid REFERENCES public.topics(id), title text NOT NULL, description text NOT NULL DEFAULT '', resource_type text NOT NULL CHECK(resource_type IN ('question_paper','marking_scheme','topic_questions','solutions','notes')), year int CHECK(year BETWEEN 1990 AND 2100), file_path text NOT NULL, preview_url text, access_level public.access_level NOT NULL DEFAULT 'free', is_published boolean NOT NULL DEFAULT true, download_count bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.resources TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.resources TO authenticated; GRANT ALL ON public.resources TO service_role; ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
CREATE POLICY "free resources public" ON public.resources FOR SELECT USING ((is_published AND access_level='free') OR public.is_admin()); CREATE POLICY "resources admin manage" ON public.resources FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE INDEX resources_browse_idx ON public.resources(program_id,subject_id,topic_id,year,resource_type);

CREATE TABLE public.videos (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), program_id uuid NOT NULL REFERENCES public.programs(id), subject_id uuid NOT NULL REFERENCES public.subjects(id), topic_id uuid REFERENCES public.topics(id), title text NOT NULL, description text NOT NULL DEFAULT '', provider text NOT NULL, provider_id text NOT NULL, provider_url text, thumbnail_url text, duration_seconds int, access_level public.access_level NOT NULL DEFAULT 'free', is_published boolean NOT NULL DEFAULT true, view_count bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.videos TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.videos TO authenticated; GRANT ALL ON public.videos TO service_role; ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "free videos public" ON public.videos FOR SELECT USING ((is_published AND access_level='free') OR public.is_admin()); CREATE POLICY "videos admin manage" ON public.videos FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE TABLE public.tutor_applications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, full_name text NOT NULL, email text NOT NULL, phone text NOT NULL, subjects text[] NOT NULL DEFAULT '{}', topics text[] NOT NULL DEFAULT '{}', qualifications text NOT NULL, years_experience int NOT NULL CHECK(years_experience>=0), pricing jsonb NOT NULL DEFAULT '{}'::jsonb, biography text NOT NULL, photo_path text, cv_path text, status public.application_status NOT NULL DEFAULT 'pending', admin_feedback text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.tutor_applications TO authenticated; GRANT ALL ON public.tutor_applications TO service_role; ALTER TABLE public.tutor_applications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "applications own read" ON public.tutor_applications FOR SELECT TO authenticated USING (auth.uid()=user_id OR public.is_admin()); CREATE POLICY "applications own create" ON public.tutor_applications FOR INSERT TO authenticated WITH CHECK (auth.uid()=user_id); CREATE POLICY "applications own pending update" ON public.tutor_applications FOR UPDATE TO authenticated USING ((auth.uid()=user_id AND status IN ('pending','changes_requested')) OR public.is_admin()) WITH CHECK (auth.uid()=user_id OR public.is_admin());

CREATE TABLE public.tutor_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE, application_id uuid UNIQUE REFERENCES public.tutor_applications(id), display_name text NOT NULL, photo_url text, bio text NOT NULL, subjects text[] NOT NULL DEFAULT '{}', topics text[] NOT NULL DEFAULT '{}', qualifications text[] NOT NULL DEFAULT '{}', years_experience int NOT NULL DEFAULT 0, pricing jsonb NOT NULL DEFAULT '{}'::jsonb, rating numeric(2,1) NOT NULL DEFAULT 0, review_count int NOT NULL DEFAULT 0, is_approved boolean NOT NULL DEFAULT false, is_visible boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.tutor_profiles TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.tutor_profiles TO authenticated; GRANT ALL ON public.tutor_profiles TO service_role; ALTER TABLE public.tutor_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "approved tutors public" ON public.tutor_profiles FOR SELECT USING ((is_approved AND is_visible) OR auth.uid()=user_id OR public.is_admin()); CREATE POLICY "tutor own update" ON public.tutor_profiles FOR UPDATE TO authenticated USING (auth.uid()=user_id OR public.is_admin()) WITH CHECK (auth.uid()=user_id OR public.is_admin()); CREATE POLICY "tutor admin create" ON public.tutor_profiles FOR INSERT TO authenticated WITH CHECK (public.is_admin()); CREATE POLICY "tutor admin delete" ON public.tutor_profiles FOR DELETE TO authenticated USING (public.is_admin());

CREATE TABLE public.tutor_availability (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tutor_id uuid NOT NULL REFERENCES public.tutor_profiles(id) ON DELETE CASCADE, day_of_week int NOT NULL CHECK(day_of_week BETWEEN 0 AND 6), start_time time NOT NULL, end_time time NOT NULL, timezone text NOT NULL DEFAULT 'Africa/Lagos', is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.tutor_availability TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.tutor_availability TO authenticated; GRANT ALL ON public.tutor_availability TO service_role; ALTER TABLE public.tutor_availability ENABLE ROW LEVEL SECURITY;
CREATE POLICY "availability public read" ON public.tutor_availability FOR SELECT USING (true); CREATE POLICY "availability tutor manage" ON public.tutor_availability FOR ALL TO authenticated USING (EXISTS(SELECT 1 FROM public.tutor_profiles t WHERE t.id=tutor_id AND (t.user_id=auth.uid() OR public.is_admin()))) WITH CHECK (EXISTS(SELECT 1 FROM public.tutor_profiles t WHERE t.id=tutor_id AND (t.user_id=auth.uid() OR public.is_admin())));

CREATE TABLE public.subscription_plans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, interval text NOT NULL, price_ngn int NOT NULL, price_usd numeric(10,2), features jsonb NOT NULL DEFAULT '[]'::jsonb, access_level public.access_level NOT NULL, is_active boolean NOT NULL DEFAULT true, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.subscription_plans TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.subscription_plans TO authenticated; GRANT ALL ON public.subscription_plans TO service_role; ALTER TABLE public.subscription_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "plans public read" ON public.subscription_plans FOR SELECT USING (is_active OR public.is_admin()); CREATE POLICY "plans admin manage" ON public.subscription_plans FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE TABLE public.premium_subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, plan_id uuid NOT NULL REFERENCES public.subscription_plans(id), status text NOT NULL CHECK(status IN ('active','past_due','cancelled','expired')), starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, provider text, provider_reference text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.premium_subscriptions TO authenticated; GRANT ALL ON public.premium_subscriptions TO service_role; ALTER TABLE public.premium_subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "subscriptions own read" ON public.premium_subscriptions FOR SELECT TO authenticated USING (auth.uid()=user_id OR public.is_admin()); CREATE POLICY "subscriptions admin manage" ON public.premium_subscriptions FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE TABLE public.bookings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_id uuid NOT NULL, tutor_id uuid NOT NULL REFERENCES public.tutor_profiles(id), subject_id uuid NOT NULL REFERENCES public.subjects(id), topic_id uuid REFERENCES public.topics(id), preferred_start timestamptz NOT NULL, duration_minutes int NOT NULL DEFAULT 60 CHECK(duration_minutes BETWEEN 30 AND 240), session_type text NOT NULL CHECK(session_type IN ('google_meet','zoom','whatsapp_coordination')), price_amount numeric(12,2) NOT NULL, currency text NOT NULL DEFAULT 'NGN', status public.booking_status NOT NULL DEFAULT 'pending', meeting_url text, student_notes text, admin_notes text, whatsapp_sent boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.bookings TO authenticated; GRANT ALL ON public.bookings TO service_role; ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "student bookings" ON public.bookings FOR SELECT TO authenticated USING (auth.uid()=student_id OR public.is_admin() OR EXISTS(SELECT 1 FROM public.tutor_profiles t WHERE t.id=tutor_id AND t.user_id=auth.uid())); CREATE POLICY "student create booking" ON public.bookings FOR INSERT TO authenticated WITH CHECK (auth.uid()=student_id); CREATE POLICY "booking participants update" ON public.bookings FOR UPDATE TO authenticated USING (auth.uid()=student_id OR public.is_admin() OR EXISTS(SELECT 1 FROM public.tutor_profiles t WHERE t.id=tutor_id AND t.user_id=auth.uid())) WITH CHECK (auth.uid()=student_id OR public.is_admin() OR EXISTS(SELECT 1 FROM public.tutor_profiles t WHERE t.id=tutor_id AND t.user_id=auth.uid()));
CREATE INDEX bookings_time_idx ON public.bookings(tutor_id,preferred_start,status);

CREATE TABLE public.payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, booking_id uuid REFERENCES public.bookings(id), subscription_id uuid REFERENCES public.premium_subscriptions(id), provider text NOT NULL CHECK(provider IN ('paystack','flutterwave','stripe')), provider_reference text UNIQUE, amount numeric(12,2) NOT NULL, currency text NOT NULL, status public.payment_status NOT NULL DEFAULT 'pending', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.payments TO authenticated; GRANT ALL ON public.payments TO service_role; ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "payments own read" ON public.payments FOR SELECT TO authenticated USING (auth.uid()=user_id OR public.is_admin());

CREATE TABLE public.attendance (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), booking_id uuid NOT NULL UNIQUE REFERENCES public.bookings(id) ON DELETE CASCADE, student_id uuid NOT NULL, tutor_id uuid NOT NULL REFERENCES public.tutor_profiles(id), attended boolean, notes text, recorded_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.attendance TO authenticated; GRANT ALL ON public.attendance TO service_role; ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "attendance participants read" ON public.attendance FOR SELECT TO authenticated USING (auth.uid()=student_id OR public.is_admin() OR EXISTS(SELECT 1 FROM public.tutor_profiles t WHERE t.id=tutor_id AND t.user_id=auth.uid())); CREATE POLICY "attendance tutor admin manage" ON public.attendance FOR ALL TO authenticated USING (public.is_admin() OR EXISTS(SELECT 1 FROM public.tutor_profiles t WHERE t.id=tutor_id AND t.user_id=auth.uid())) WITH CHECK (public.is_admin() OR EXISTS(SELECT 1 FROM public.tutor_profiles t WHERE t.id=tutor_id AND t.user_id=auth.uid()));

CREATE TABLE public.testimonials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_name text NOT NULL, program_name text NOT NULL, quote text NOT NULL, rating int NOT NULL CHECK(rating BETWEEN 1 AND 5), photo_url text, is_published boolean NOT NULL DEFAULT false, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.testimonials TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.testimonials TO authenticated; GRANT ALL ON public.testimonials TO service_role; ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "testimonials public read" ON public.testimonials FOR SELECT USING (is_published OR public.is_admin()); CREATE POLICY "testimonials admin manage" ON public.testimonials FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE TABLE public.contact_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid, full_name text NOT NULL, email text NOT NULL, phone text, subject text NOT NULL, message text NOT NULL, status text NOT NULL DEFAULT 'new', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT INSERT ON public.contact_messages TO anon,authenticated; GRANT SELECT,UPDATE,DELETE ON public.contact_messages TO authenticated; GRANT ALL ON public.contact_messages TO service_role; ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "contact public create" ON public.contact_messages FOR INSERT WITH CHECK (user_id IS NULL OR auth.uid()=user_id); CREATE POLICY "contact admin read" ON public.contact_messages FOR SELECT TO authenticated USING (public.is_admin()); CREATE POLICY "contact admin update" ON public.contact_messages FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin()); CREATE POLICY "contact admin delete" ON public.contact_messages FOR DELETE TO authenticated USING (public.is_admin());

CREATE TABLE public.notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, title text NOT NULL, body text NOT NULL, type text NOT NULL DEFAULT 'info', is_read boolean NOT NULL DEFAULT false, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,UPDATE,DELETE ON public.notifications TO authenticated; GRANT ALL ON public.notifications TO service_role; ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "notifications own" ON public.notifications FOR SELECT TO authenticated USING (auth.uid()=user_id OR public.is_admin()); CREATE POLICY "notifications own update" ON public.notifications FOR UPDATE TO authenticated USING (auth.uid()=user_id) WITH CHECK (auth.uid()=user_id);

CREATE TABLE public.analytics_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid, event_name text NOT NULL, entity_type text, entity_id uuid, properties jsonb NOT NULL DEFAULT '{}'::jsonb, session_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT INSERT ON public.analytics_events TO anon,authenticated; GRANT SELECT ON public.analytics_events TO authenticated; GRANT ALL ON public.analytics_events TO service_role; ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "analytics collect" ON public.analytics_events FOR INSERT WITH CHECK (user_id IS NULL OR auth.uid()=user_id); CREATE POLICY "analytics admin read" ON public.analytics_events FOR SELECT TO authenticated USING (public.is_admin()); CREATE INDEX analytics_event_idx ON public.analytics_events(event_name,created_at);

CREATE TABLE public.saved_resources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, resource_id uuid NOT NULL REFERENCES public.resources(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,resource_id));
GRANT SELECT,INSERT,DELETE ON public.saved_resources TO authenticated; GRANT ALL ON public.saved_resources TO service_role; ALTER TABLE public.saved_resources ENABLE ROW LEVEL SECURITY;
CREATE POLICY "saved own manage" ON public.saved_resources FOR ALL TO authenticated USING (auth.uid()=user_id) WITH CHECK (auth.uid()=user_id);

CREATE TABLE public.learning_activity (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, topic_id uuid REFERENCES public.topics(id), resource_id uuid REFERENCES public.resources(id), video_id uuid REFERENCES public.videos(id), activity_type text NOT NULL, progress numeric(5,2) NOT NULL DEFAULT 0 CHECK(progress BETWEEN 0 AND 100), last_viewed_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.learning_activity TO authenticated; GRANT ALL ON public.learning_activity TO service_role; ALTER TABLE public.learning_activity ENABLE ROW LEVEL SECURITY;
CREATE POLICY "activity own manage" ON public.learning_activity FOR ALL TO authenticated USING (auth.uid()=user_id) WITH CHECK (auth.uid()=user_id);

CREATE TABLE public.founder_profile (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, title text NOT NULL, biography text NOT NULL, photo_url text, mission text NOT NULL, vision text NOT NULL, philosophy text NOT NULL, journey jsonb NOT NULL DEFAULT '[]'::jsonb, achievements jsonb NOT NULL DEFAULT '[]'::jsonb, is_published boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.founder_profile TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.founder_profile TO authenticated; GRANT ALL ON public.founder_profile TO service_role; ALTER TABLE public.founder_profile ENABLE ROW LEVEL SECURITY;
CREATE POLICY "founder public read" ON public.founder_profile FOR SELECT USING (is_published OR public.is_admin()); CREATE POLICY "founder admin manage" ON public.founder_profile FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE TABLE public.settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text NOT NULL UNIQUE, value jsonb NOT NULL, is_public boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.settings TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.settings TO authenticated; GRANT ALL ON public.settings TO service_role; ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "settings public read" ON public.settings FOR SELECT USING (is_public OR public.is_admin()); CREATE POLICY "settings admin manage" ON public.settings FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['profiles','user_roles','programs','subjects','topics','resources','videos','tutor_applications','tutor_profiles','tutor_availability','subscription_plans','premium_subscriptions','bookings','payments','attendance','testimonials','contact_messages','notifications','analytics_events','saved_resources','learning_activity','founder_profile','settings'] LOOP EXECUTE format('CREATE TRIGGER set_%I_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()',t,t); END LOOP; END $$;

INSERT INTO public.programs(name,slug,description,accent,sort_order) VALUES ('Cambridge','cambridge','Rigorous Cambridge Mathematics pathways built for confident problem-solving and measurable exam progress.','blue',1),('IGCSE','igcse','Focused IGCSE preparation with structured practice, expert explanations, and exam-ready skills.','orange',2);
INSERT INTO public.subjects(program_id,name,slug,description,sort_order) SELECT id,'Mathematics','mathematics','Core and advanced mathematics resources, lessons, and tutor support.',1 FROM public.programs;
INSERT INTO public.subjects(program_id,name,slug,description,sort_order) SELECT id,'Further Mathematics','further-mathematics','Advanced mathematical reasoning for ambitious Cambridge learners.',2 FROM public.programs WHERE slug='cambridge';
INSERT INTO public.topics(subject_id,name,slug,description,sort_order) SELECT s.id,v.name,v.slug,v.description,v.ord FROM public.subjects s CROSS JOIN (VALUES ('Algebra','algebra','Build fluency in expressions, equations, and mathematical structure.',1),('Functions','functions','Understand mappings, graphs, transformations, and inverse functions.',2),('Trigonometry','trigonometry','Master identities, equations, graphs, and geometric applications.',3),('Calculus','calculus','Develop confident differentiation and integration techniques.',4),('Vectors','vectors','Explore vector geometry, magnitude, direction, and proofs.',5),('Statistics','statistics','Interpret data, distributions, and statistical models.',6),('Probability','probability','Model uncertainty through structured probability methods.',7),('Coordinate Geometry','coordinate-geometry','Connect algebra and geometry using lines, curves, and coordinates.',8),('Series','series','Analyze sequences, progressions, and summation methods.',9),('Mechanics','mechanics','Apply mathematics to forces, motion, and physical models.',10)) AS v(name,slug,description,ord);
INSERT INTO public.subscription_plans(name,slug,interval,price_ngn,price_usd,features,access_level,sort_order) VALUES ('Free','free','forever',0,0,'["Free lesson videos","Selected past questions","Tutor discovery"]','free',1),('Premium Monthly','premium-monthly','month',500000,4.00,'["All premium videos","Premium topic resources","Worked examples","Priority learning support"]','premium',2),('Premium Quarterly','premium-quarterly','quarter',1250000,10.00,'["All premium videos","Premium topic resources","Worked examples","Priority learning support"]','premium',3),('Premium Annual','premium-annual','year',4500000,36.00,'["All premium videos","Premium topic resources","Worked examples","Priority learning support","Best value"]','premium',4);
INSERT INTO public.founder_profile(name,title,biography,mission,vision,philosophy,journey,achievements) VALUES ('Ahmed Thaoban','Founder','Founder biography will be updated from the Admin Dashboard.','Make high-quality Mathematics learning personal, structured, and accessible.','Build a trusted academic ecosystem where every learner can catch up and stay ahead.','Students grow fastest when clear explanations, deliberate practice, and expert mentorship work together.','[{"year":"Foundation","title":"CatchUp Tutors begins","text":"Created to help learners turn academic gaps into lasting confidence."}]','["Cambridge and IGCSE focus","Student-first learning design"]');
INSERT INTO public.settings(key,value,is_public) VALUES ('contact','{"email":"Catchuptutors01@gmail.com","support_email":"support@catchuptutors.com","whatsapp":"2348101804411","countries":["Nigeria","United Kingdom"]}',true),('social_links','{"youtube":"https://youtube.com/@catch-uptutors2691?si=9YKS7NsmOUOdU96f","instagram":"https://www.instagram.com/tutors.catchup?igsh=MXB4cmgzdGVucjM0aw==","facebook":"https://www.facebook.com/share/1BTRMp9BPw/"}',true),('payments','{"currencies":["NGN","USD"],"providers":["paystack","flutterwave"]}',true),('platform','{"name":"CatchUp Tutors","tagline":"Catch Up. Stay Ahead."}',true);